import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

import { ObjectPreview } from "@/components/assets/object-preview";
import {
  SHOWCASE_ASSETS,
  type ShowcaseAsset,
} from "@/components/assets/asset-showcase-data";

/**
 * The three shipped asset-pack objects, shown as live previews of the same GLBs
 * the asset pack serves. Each card deep links into `/asset-pack`, which selects
 * an asset from the URL hash. Physical values carry a stated confidence
 * interval to match the "predicted by the pipeline, validated against the real
 * object" pitch.
 */
function ObjectCard({ object }: { object: ShowcaseAsset }) {
  return (
    <Link
      href={object.href}
      className="card-flat group flex h-full flex-col overflow-hidden rounded-md transition-colors hover:border-graphite focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
    >
      <article className="flex h-full flex-col">
        <div className="relative aspect-4/3 w-full overflow-hidden border-b border-border bg-(--void)">
          <ObjectPreview url={object.url} fit={object.fit} />
        </div>
        <div className="flex flex-col gap-3 p-4">
          <h3 className="flex items-center gap-1.5 text-lg leading-tight text-foreground">
            {object.title}
            <ArrowUpRight className="size-4 shrink-0 text-dim transition-colors group-hover:text-foreground" />
          </h3>
          <dl className="data grid grid-cols-2 gap-x-4 gap-y-2 text-[0.65rem]">
            {object.specs.map((s) => (
              <div key={s.label} className="flex flex-col gap-0.5">
                <dt className="uppercase text-dim">{s.label}</dt>
                <dd className="text-ash">{s.value}</dd>
              </div>
            ))}
          </dl>
        </div>
      </article>
    </Link>
  );
}

export function AssetGallery() {
  return (
    <section
      id="gallery"
      className="relative z-10 border-b border-border bg-background"
    >
      <div className="mx-auto max-w-6xl px-6 py-16 md:py-20">
        <div className="mb-10 text-center">
          <div className="eyebrow mb-4">Shipped assets</div>
          <h2 className="text-3xl leading-[1.1] text-foreground md:text-4xl">
            Built and validated.
          </h2>
          <p className="prose-body mx-auto mt-4">
            Every physical value on these assets was generated by our Real2Sim
            pipeline and validated against the real object, with stated
            confidence.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {SHOWCASE_ASSETS.map((object) => (
            <ObjectCard key={object.slug} object={object} />
          ))}
        </div>
        <div className="mt-8 text-center">
          <Link
            href="/asset-pack"
            className="text-[0.8125rem] text-body underline-offset-4 hover:text-foreground hover:underline"
          >
            Open the asset pack
          </Link>
        </div>
      </div>
    </section>
  );
}
